#!/command/with-contenv bash
set -e
exec 2>&1
cd /opt/zai
export PORT="${ZAI_PORT:-3001}"
export HOST="${BIND_ADDR:-0.0.0.0}"
export TIMEOUT="${ZAI_TIMEOUT:-300000}"
export AUTH_TOKEN="${ZAI_AUTH_TOKEN:-Waguri}"
export ZAI_TOKEN="${ZAI_TOKEN:-}"
export AGENT_MODE="${ZAI_AGENT_MODE:-true}"
export AGENT_MODE_VARIANT="${ZAI_AGENT_MODE_VARIANT:-modern}"
export STREAM_HOLDBACK="${ZAI_STREAM_HOLDBACK:-24}"
export LOG_LEVEL="${ZAI_LOG_LEVEL:-info}"
export SYNC_MODE="${ZAI_SYNC_MODE:-false}"
export SESSION_POOL_SIZE="${ZAI_SESSION_POOL_SIZE:-5}"
export UPSTREAM_MIN_INTERVAL_MS="${ZAI_UPSTREAM_MIN_INTERVAL_MS:-200}"
export SESSION_ACQUIRE_TIMEOUT="${ZAI_SESSION_ACQUIRE_TIMEOUT:-10}"
export LOG_FORMAT="${ZAI_LOG_FORMAT:-text}"


export HTTP_PROXY="http://127.0.0.1:${ZAI_PROXY_PORT:-2001}"
export HTTPS_PROXY="http://127.0.0.1:${ZAI_PROXY_PORT:-2001}"
export ALL_PROXY="http://127.0.0.1:${ZAI_PROXY_PORT:-2001}"
export NO_PROXY="localhost,127.0.0.1"

./token-collector collect --tokens 850 --batch 5 --no-tui --block-trackers --parallel 2

exec ./zai-api
